### ISSUE TITLE
Cara makenya gimana 

### ISSUE THREAD

**Issue by amrdevac** [jfalih/react-native-scroll-up-container#1]
![image](https://user-images.githubusercontent.com/90322346/155092365-525e5474-898e-4673-b5e8-1f80949eee8b.png)
udah di install hasil nya cuma gini aja , ga bisa di scroll juga 0,0

**Comment by jfalih** [comment]
Untuk penggunaan bisa explore dulu seperti yang ada pada props yahh jika ada bug atau masalah silahkan pull request terimakasih..
